# Generated by Django 6.0.7 on 2026-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_personmovie_starrole_movie_director_movie_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonMovie',
        ),
        migrations.DeleteModel(
            name='StarRole',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
